"""Added new column to users

Revision ID: b3843f9ac421
Revises: 2388aa68d669
Create Date: 2025-10-08 23:04:38.056579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3843f9ac421'
down_revision: Union[str, Sequence[str], None] = '2388aa68d669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('followup_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message_template', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_table('message_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('message_data', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_queue_id'), 'message_queue', ['id'], unique=False)
    op.add_column('conversations', sa.Column('sender', sa.String(), nullable=False))
    op.add_column('conversations', sa.Column('parent_message_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('delivery_status', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('intent_detected', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.alter_column('conversations', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'conversations', 'conversations', ['parent_message_id'], ['id'])
    op.add_column('leads', sa.Column('lead_status', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('response_received', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('followup_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('last_followup_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_followup_at')
    op.drop_column('leads', 'followup_count')
    op.drop_column('leads', 'response_received')
    op.drop_column('leads', 'message_count')
    op.drop_column('leads', 'last_message_at')
    op.drop_column('leads', 'last_contacted_at')
    op.drop_column('leads', 'lead_status')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('conversations', 'meta_data')
    op.drop_column('conversations', 'intent_detected')
    op.drop_column('conversations', 'read_at')
    op.drop_column('conversations', 'delivery_status')
    op.drop_column('conversations', 'message_id')
    op.drop_column('conversations', 'parent_message_id')
    op.drop_column('conversations', 'sender')
    op.drop_index(op.f('ix_message_queue_id'), table_name='message_queue')
    op.drop_table('message_queue')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
